### ISSUE TITLE
Running example fails with UnboundLocalError: local variable 'integrand1' referenced before assignment ...

### ISSUE THREAD

**Issue by mfeldt** [tomasstolker/species#46]
Simply following the initial steps on https://species.readthedocs.io/en/latest/tutorials/running_species.html after a fresh pip install. When doing the 

`database.add_companion('51 Eri b')`

The result is the following error...:

```
>>> database.add_companion('51 Eri b')
Downloading Vega spectrum (270 kB)... [DONE]
Adding Vega spectrum... [DONE]
Adding filter: MKO/NSFCam.J... [DONE]
Adding filter: MKO/NSFCam.H... [DONE]
Adding filter: MKO/NSFCam.K... [DONE]
Adding filter: Paranal/SPHERE.IRDIS_B_H... [DONE]
Adding filter: Paranal/SPHERE.IRDIS_D_H23_2... [DONE]
Adding filter: Paranal/SPHERE.IRDIS_D_K12_1... [DONE]
Adding filter: Keck/NIRC2.Lp... [DONE]
Adding filter: Keck/NIRC2.Ms... [DONE]
Adding object: 51 Eri b
   - Distance (pc) = 29.78 +/- 0.12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/typeguard/__init__.py", line 891, in wrapper
    retval = func(*args, **kwargs)
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/species/data/database.py", line 171, in add_companion
    self.add_object(object_name=item,
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/typeguard/__init__.py", line 891, in wrapper
    retval = func(*args, **kwargs)
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/species/data/database.py", line 657, in add_object
    flux[mag_item], error[mag_item] = synphot.magnitude_to_flux(
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/typeguard/__init__.py", line 891, in wrapper
    retval = func(*args, **kwargs)
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/species/analysis/photometry.py", line 344, in magnitude_to_flux
    zp_flux = self.zero_point()
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/typeguard/__init__.py", line 891, in wrapper
    retval = func(*args, **kwargs)
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/species/analysis/photometry.py", line 101, in zero_point
    return self.spectrum_to_flux(wavelength_crop, flux_crop)[0]
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/typeguard/__init__.py", line 891, in wrapper
    retval = func(*args, **kwargs)
  File "/home/feldt/miniconda3/envs/petitRADTRANS/lib/python3.9/site-packages/species/analysis/photometry.py", line 208, in spectrum_to_flux
    integral1 = np.trapz(integrand1, wavelength[indices])
UnboundLocalError: local variable 'integrand1' referenced before assignment
```

Looks like no detector type gets ever assigned...

**Comment by tomasstolker** [comment]
Thanks for opening this issue @mfeldt!

The problem is related to an update on the website of the SVO Filter Profile Service. The specification of the detector type had changed.

Which version of ``species`` are you using? The latest pip version (0.3.6) should be compatible with the changes by SVO but let me know if that doesn't solve the problem.

**Comment by mfeldt** [comment]
I freshly installed it this morning (with pip) after Paul pointed me to the package, and it came up as 0.3.4

Maybe some pip data base is not up to date yet?

**Comment by tomasstolker** [comment]
Yes that could be. I am not sure how this works with Miniconda. Is there a way to sync Miniconda with the PyPI server?

The ``species`` version on the PyPI server is up to date:
https://pypi.org/project/species/

Otherwise, you could also install the Github version. That should also work.

**Comment by mfeldt** [comment]
OK; I'll give it a try!

**Comment by mfeldt** [comment]
OK, I managed to upgrade to 0.3.6 (turns out there were some unfullfilled sub-sub requirements about ultranest...)

The error, however, is still there!

**Comment by tomasstolker** [comment]
Could you remove the `species_database.hdf5` file and try once more?

Then it will download again the filter profile and (hopefully) store it correctly in the database this time.

Does that work?

**Comment by mfeldt** [comment]
Actually I cannot  find that file...

**Comment by mfeldt** [comment]
Ah, ok, got it. Yes, that did the trick! 

  THX!

**Comment by tomasstolker** [comment]
Great, glad it worked!
